site_name: DataVis
repo_url: https://repo.mieweb.com/projects/DV/repos/wcdatavis/
site_author: Taylor Venable <tvenable@mieweb.com>
theme:
  name: material
  feature:
    tabs: false
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Overpass'
    code: 'Overpass Mono'
docs_dir: doc/md
site_dir: doc/html
extra_javascript:
  - mermaid.min.js
extra_css:
  - style.css
nav:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Architectural Overview: overview.md
  - Sources:
      - Source Basics: source/index.md
      - Builtin Sources: source/builtin.md
      - Writing Your Own: source/custom.md
  - View:
      - Primary Operations: view/view.md
      - Group Functions: view/group_funs.md
  - Grid:
      - Overview: grid/index.md
      - Renderers:
          - Table: grid/renderers/table.md
          - Handlebars: grid/renderers/handlebars.md
      - Operations: grid/operations.md
  - Graph:
      - Overview: graph/index.md
      - Gantt Charts: graph/gantt.md
  - Types: types.md
  - Preferences: prefs.md
  - Performance: performance.md
  - Errors & Debugging: debugging.md
  - Localization: localization.md
  - Development:
      - Getting Started: development/index.md
      - Best Practices: development/standards.md
      - Generating Data: development/json_gen.md
      - Testing: development/testing.md
      - Documentation: development/docs.md
      - Making a Release: development/release.md
  - Utilization:
      - Known Issues: known_issues.md
  - Glossary: glossary.md
  - About DataVis: about.md
# SEE ALSO: https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:
  - markdown.extensions.extra
  - markdown.extensions.admonition
  - markdown.extensions.codehilite: # needed only for material theme
      guess_lang: false
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
